import Header from '@/src/components/Header/Header'
import './font.css'
import '../src/styles/common.scss'
import './globals.scss'
import Footer from '@/src/components/Footer/Footer'
import Providers from '@/src/components/Providers/Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className='h-[5rem]' /> {/* Whitespace */}
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
